#!/usr/bin/env python3
"""Makes every app icon and logo size from the art in branding/ (#106).

Run from anywhere; needs Pillow (`pip install pillow`). Writes:

  ios/Runner/Assets.xcassets/AppIcon.appiconset  every size its
      Contents.json lists, white, no alpha (iOS rounds the corners)
  android/app/src/main/res/mipmap-*/ic_launcher.png  pre-Android 8
  android/app/src/main/res/drawable-*/ic_launcher_foreground.png and
      mipmap-anydpi-v26/ic_launcher.xml  the adaptive icon, on white
  branding/store/app-store-icon-1024.png  App Store Connect (no alpha)
  branding/store/play-icon-512.png        Google Play
  assets/spliit2go-logo.png (+ 2.0x/, 3.0x/)  the group list header, 28 pt

See SETUP.md, "App icon".
"""
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
BRANDING = ROOT / 'branding'

# The transparent art has faint colored noise left from background
# removal (alpha 1-16) and nearly opaque fills (alpha 250-254); snap both.
NOISE_ALPHA = 16
OPAQUE_ALPHA = 250

# Android masks the adaptive foreground (108 dp) to a shape that always
# contains the central 66 dp circle; keep the art inside it.
ADAPTIVE_SAFE_RADIUS = 33 / 108
# The square icons (iOS, the stores) leave a 10% margin: the plane's nose
# and tail reach sideways, and at Android's fill (33 of 72 dp) they touch
# the edges of iOS's rounded icon.
ICON_REACH = 0.40

HEADER_POINTS = 28

IOS_ICONS = ROOT / 'ios' / 'Runner' / 'Assets.xcassets' / 'AppIcon.appiconset'
ANDROID_RES = ROOT / 'android' / 'app' / 'src' / 'main' / 'res'
# Launcher icons are 48 dp; adaptive icon layers are 108 dp.
ANDROID_DENSITIES = {'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4}

ADAPTIVE_ICON_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make_icons.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@android:color/white"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
"""


def clean(img):
    alpha = img.getchannel('A').point(
        lambda a: 0 if a <= NOISE_ALPHA else 255 if a >= OPAQUE_ALPHA else a)
    img = img.copy()
    img.putalpha(alpha)
    return img


def resized(img, size):
    return img.resize((size, size), Image.LANCZOS)


def flatten(img):
    """On white, without an alpha channel (the App Store rejects one)."""
    white = Image.new('RGBA', img.size, (255, 255, 255, 255))
    white.alpha_composite(img)
    return white.convert('RGB')


def centered(art, reach, size=1024):
    """The art centered on its bounding box, scaled so every visible pixel
    lies within [reach] of the center (a fraction of [size])."""
    box = art.getbbox()
    art = art.crop(box)
    cx, cy = art.width / 2, art.height / 2
    alpha = art.getchannel('A').load()
    reach_px = max(
        ((x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2) ** 0.5
        for y in range(0, art.height, 2)
        for x in range(0, art.width, 2)
        if alpha[x, y] > 0)
    scale = reach * size / reach_px
    art = art.resize((round(art.width * scale), round(art.height * scale)), Image.LANCZOS)
    canvas = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    canvas.alpha_composite(art, ((size - art.width) // 2, (size - art.height) // 2))
    return canvas


def header_logo(art):
    """Cropped to the art and padded square, so 28 pt is all logo."""
    art = art.crop(art.getbbox())
    side = max(art.size)
    square = Image.new('RGBA', (side, side), (0, 0, 0, 0))
    square.alpha_composite(art, ((side - art.width) // 2, (side - art.height) // 2))
    return square


def save(img, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path, optimize=True)
    print(f'{path.relative_to(ROOT)}  {img.width}x{img.height} {img.mode}')


def main():
    art = clean(Image.open(BRANDING / 'spliit2go-logo-serious.png').convert('RGBA'))
    white = flatten(centered(art, ICON_REACH))

    for image in json.loads((IOS_ICONS / 'Contents.json').read_text())['images']:
        points = float(image['size'].split('x')[0])
        scale = int(image['scale'].rstrip('x'))
        save(resized(white, round(points * scale)), IOS_ICONS / image['filename'])

    foreground = centered(art, ADAPTIVE_SAFE_RADIUS)
    for density, ratio in ANDROID_DENSITIES.items():
        save(resized(white, round(48 * ratio)), ANDROID_RES / f'mipmap-{density}' / 'ic_launcher.png')
        save(resized(foreground, round(108 * ratio)),
             ANDROID_RES / f'drawable-{density}' / 'ic_launcher_foreground.png')
    adaptive = ANDROID_RES / 'mipmap-anydpi-v26' / 'ic_launcher.xml'
    adaptive.parent.mkdir(exist_ok=True)
    adaptive.write_text(ADAPTIVE_ICON_XML)
    print(adaptive.relative_to(ROOT))

    save(resized(white, 1024), BRANDING / 'store' / 'app-store-icon-1024.png')
    save(resized(white, 512), BRANDING / 'store' / 'play-icon-512.png')

    logo = header_logo(art)
    for ratio, folder in [(1, ''), (2, '2.0x'), (3, '3.0x')]:
        save(resized(logo, HEADER_POINTS * ratio), ROOT / 'assets' / folder / 'spliit2go-logo.png')


if __name__ == '__main__':
    main()
