#!/usr/bin/env python3
"""Makes every app icon and logo size from the art in branding/ (#106).

Run from anywhere; needs Pillow (`pip install pillow`). Writes:

  ios/Runner/Assets.xcassets/AppIcon.appiconset  every size its
      Contents.json lists, on ICON_BACKGROUND, no alpha (iOS rounds the corners)
  android/app/src/main/res/mipmap-*/ic_launcher.png  pre-Android 8
  android/app/src/main/res/drawable-*/ic_launcher_{foreground,monochrome}.png,
      values/ic_launcher_background.xml and mipmap-anydpi-v26/ic_launcher.xml
      the adaptive icon's three layers (background, foreground, and the
      monochrome layer Android 13+ tints for themed icons)
  branding/store/app-store-icon-1024.png  App Store Connect (no alpha)
  branding/store/play-icon-512.png        Google Play
  assets/spliit2go-logo.png (+ 2.0x/, 3.0x/)  the group list header, 32 pt,
      the logo in a HEADER_BACKGROUND circle like the launcher icon

See SETUP.md, "App icon".
"""
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
BRANDING = ROOT / 'branding'

# The transparent art has faint colored noise left from background
# removal (alpha 1-16) and nearly opaque fills (alpha 250-254); snap both.
NOISE_ALPHA = 16
OPAQUE_ALPHA = 250

# The solid background of branding/spliit2go-icon.png, which is the logo
# on this color; the icons are built from the transparent logo on it.
BACKGROUND = (0xA2, 0xE0, 0xD5)


def lighter(color, fraction):
    """[color] moved [fraction] of the way to white."""
    return tuple(round(c + (255 - c) * fraction) for c in color)


# The art's teal looked dim on a phone; Ken compared mockups at 25%, 50% and
# 75% toward white (2026-10-01) and chose 50% for the icons, #D0F0EA. The
# header logo takes 25%, #B9E8E0: on the near-white light-mode app bar a
# lighter circle loses its edge.
ICON_BACKGROUND = lighter(BACKGROUND, 0.5)
HEADER_BACKGROUND = lighter(BACKGROUND, 0.25)

# Android masks the adaptive foreground (108 dp) to a shape that always
# contains the central 66 dp circle; keep the art inside it.
ADAPTIVE_SAFE_RADIUS = 33 / 108
# The square icons (iOS, the stores) leave a 10% margin: the plane's nose
# and tail reach sideways, and at Android's fill (33 of 72 dp) they touch
# the edges of iOS's rounded icon.
ICON_REACH = 0.40

HEADER_POINTS = 32
# The header's circle frames the art as Android's launcher does: the safe
# circle's 33 dp within the 36 dp radius it shows.
HEADER_REACH = 33 / 72

IOS_ICONS = ROOT / 'ios' / 'Runner' / 'Assets.xcassets' / 'AppIcon.appiconset'
ANDROID_RES = ROOT / 'android' / 'app' / 'src' / 'main' / 'res'
# Launcher icons are 48 dp; adaptive icon layers are 108 dp.
ANDROID_DENSITIES = {'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4}

ADAPTIVE_ICON_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make_icons.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
</adaptive-icon>
"""

BACKGROUND_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make_icons.py. -->
<resources>
    <color name="ic_launcher_background">#{:02X}{:02X}{:02X}</color>
</resources>
""".format(*ICON_BACKGROUND)


def clean(img):
    alpha = img.getchannel('A').point(
        lambda a: 0 if a <= NOISE_ALPHA else 255 if a >= OPAQUE_ALPHA else a)
    img = img.copy()
    img.putalpha(alpha)
    return img


def resized(img, size):
    return img.resize((size, size), Image.LANCZOS)


def flatten(img):
    """On ICON_BACKGROUND, without an alpha channel (the App Store rejects one)."""
    square = Image.new('RGBA', img.size, ICON_BACKGROUND + (255,))
    square.alpha_composite(img)
    return square.convert('RGB')


def monochrome(art):
    """The art as one shape for Android's themed icon, which keeps only the
    alpha: the plane and the banknote's dark green details are solid; the
    plane's window, stripe and engine, the white trail between plane and
    banknote, and the banknote's light green are cut out, so the two stay
    apart."""
    def weight(rgba):
        r, g, b, a = rgba
        if r - g > 30:  # the plane: coral solid, dark red cut out
            w = (r - 170) / 40
        else:  # the banknote and the trail: dark green (g <= 192) solid
            w = (196 - g) / 6 + 0.5
        return round(a * min(max(w, 0), 1))
    mask = Image.new('L', art.size)
    src, dst = art.load(), mask.load()
    for y in range(art.height):
        for x in range(art.width):
            dst[x, y] = weight(src[x, y])
    # The banknote's rim is soft in the art; blur and cut again so its edge
    # comes out smooth instead of speckled.
    mask = mask.filter(ImageFilter.GaussianBlur(art.width / 512)).point(
        lambda v: min(max((v - 128) * 4 + 128, 0), 255))
    mono = Image.new('RGBA', art.size, (255, 255, 255, 0))
    mono.putalpha(mask)
    return mono


def centered(art, reach, size=1024):
    """The art centered on its bounding box, scaled so every visible pixel
    lies within [reach] of the center (a fraction of [size])."""
    box = art.getbbox()
    art = art.crop(box)
    cx, cy = art.width / 2, art.height / 2
    alpha = art.getchannel('A').load()
    reach_px = max(
        ((x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2) ** 0.5
        for y in range(0, art.height, 2)
        for x in range(0, art.width, 2)
        if alpha[x, y] > 0)
    scale = reach * size / reach_px
    art = art.resize((round(art.width * scale), round(art.height * scale)), Image.LANCZOS)
    canvas = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    canvas.alpha_composite(art, ((size - art.width) // 2, (size - art.height) // 2))
    return canvas


def header_logo(art, size=1024):
    """The logo in a HEADER_BACKGROUND circle, transparent outside it, so it sits on
    the header in light and dark mode and matches the launcher icon."""
    circle = Image.new('L', (size * 4, size * 4), 0)
    ImageDraw.Draw(circle).ellipse((0, 0, size * 4 - 1, size * 4 - 1), fill=255)
    logo = Image.new('RGBA', (size, size), HEADER_BACKGROUND + (255,))
    logo.alpha_composite(centered(art, HEADER_REACH, size))
    logo.putalpha(circle.resize((size, size), Image.LANCZOS))
    return logo


def save(img, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path, optimize=True)
    print(f'{path.relative_to(ROOT)}  {img.width}x{img.height} {img.mode}')


def main():
    art = clean(Image.open(BRANDING / 'spliit2go-logo.png').convert('RGBA'))
    square = flatten(centered(art, ICON_REACH))

    for image in json.loads((IOS_ICONS / 'Contents.json').read_text())['images']:
        points = float(image['size'].split('x')[0])
        scale = int(image['scale'].rstrip('x'))
        save(resized(square, round(points * scale)), IOS_ICONS / image['filename'])

    foreground = centered(art, ADAPTIVE_SAFE_RADIUS)
    mono = monochrome(foreground)
    for density, ratio in ANDROID_DENSITIES.items():
        save(resized(square, round(48 * ratio)), ANDROID_RES / f'mipmap-{density}' / 'ic_launcher.png')
        save(resized(foreground, round(108 * ratio)),
             ANDROID_RES / f'drawable-{density}' / 'ic_launcher_foreground.png')
        save(resized(mono, round(108 * ratio)),
             ANDROID_RES / f'drawable-{density}' / 'ic_launcher_monochrome.png')
    for path, text in [(ANDROID_RES / 'mipmap-anydpi-v26' / 'ic_launcher.xml', ADAPTIVE_ICON_XML),
                       (ANDROID_RES / 'values' / 'ic_launcher_background.xml', BACKGROUND_XML)]:
        path.parent.mkdir(exist_ok=True)
        path.write_text(text)
        print(path.relative_to(ROOT))

    save(resized(square, 1024), BRANDING / 'store' / 'app-store-icon-1024.png')
    save(resized(square, 512), BRANDING / 'store' / 'play-icon-512.png')

    logo = header_logo(art)
    for ratio, folder in [(1, ''), (2, '2.0x'), (3, '3.0x')]:
        save(resized(logo, HEADER_POINTS * ratio), ROOT / 'assets' / folder / 'spliit2go-logo.png')


if __name__ == '__main__':
    main()
